# Generated by Django 4.0.2 on 2022-02-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(default='2022-02-22 16:00'),
            preserve_default=False,
        ),
    ]
